package lt.vilniustech.YHev.first.model;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.Date;

/**
 * Entity class representing a financial transaction in the system.
 * Stores transaction details such as amount, type, and date.
 */
@Entity
@Table(name="transaction")
@XmlRootElement(name = "transaction")
@XmlType(propOrder = {"id", "amount", "type", "date"})
public class Transaction {

    /**
     * Unique identifier for the transaction.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ✅ Database generates ID
    @Column(name="id")
    private int id;

    /**
     * The amount of money involved in the transaction.
     */
    private Float amount;

    /**
     * The type of transaction (e.g., "deposit", "withdrawal", "transfer").
     */
    private String type;

    /**
     * The date when the transaction was executed.
     */
    private Date date;

    /**
     * Default constructor required by JPA.
     */
    public Transaction() {}

    /**
     * Parameterized constructor for initializing a transaction.
     *
     * @param amount The amount of the transaction.
     * @param type The type of transaction (e.g., deposit, withdrawal, transfer).
     * @param date The date when the transaction occurred.
     */
    public Transaction(Float amount, String type, Date date) {
        this.amount = amount;
        this.type = type;
        this.date = date;
    }

    /**
     * Gets the ID of the transaction.
     *
     * @return The transaction ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the ID of the transaction.
     *
     * @param id The new transaction ID.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the transaction amount.
     *
     * @return The transaction amount.
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * Sets the transaction amount.
     *
     * @param amount The new transaction amount.
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * Gets the transaction type.
     *
     * @return The transaction type.
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the transaction type.
     *
     * @param type The new transaction type.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets the transaction date.
     *
     * @return The date of the transaction.
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the transaction date.
     *
     * @param date The new transaction date.
     */
    public void setDate(Date date) {
        this.date = date;
    }
}
